# -*- coding: utf-8 -*-
"""food_access.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hpkMarXH8gEDRT584f6Zs8rAaNpTPlAS
"""

!pip install -q folium mapclassify

import geopandas as gpd
import matplotlib.pyplot as plt
import fiona
import pandas as pd

def load_data(shp_path, csv_path):
    census_data = gpd.read_file(shp_path)
    food_access = pd.read_csv(csv_path)

    census_data['CTIDFP00'] = census_data['CTIDFP00'].astype(str)
    food_access['CensusTract'] = food_access['CensusTract'].astype(str)

    return census_data.merge(food_access, how='left', left_on="CTIDFP00", right_on="CensusTract")

state_data = load_data("tl_2010_53_tract00.shp", "food_access2010.csv")
display(state_data)

def interactive_map(state_data):
  low_access_censurb = (state_data["Urban"]== 1) & (state_data["LATracts_half"]== 1)
  low_access_censrural = (state_data["Rural"]== 1) & (state_data["LATracts10"]== 1)
  low_income_tract = state_data["LowIncomeTracts"] == 1

  return state_data[low_income_tract & (low_access_censurb | low_access_censrural)].explore()

map_active = interactive_map(state_data)
map_active.save("interactive_map.html")
display(map_active)